name = "Multiworld Packwitz"
author = "Joe Blub"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9307e1c5c7225449d63ac21e407d2fcfad74033a81fa45eaa060ad6439e1ac9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
datapack-folder = "plugins/"
