name = "Multiworld Packwitz"
author = "Joe Blub"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cdd83ae54ce0d664b32a0359a0378c65d2c590b0edee94d051f95a894997206"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
