name = "Multiworld Packwitz"
author = "Joe Blub"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9aaf622fd7928f706f5bbee7d97f8304347ff7d69562981c06d229b15a4cc67e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
