name = "Multiworld Packwitz"
author = "Joe Blub"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c0adce49c72e654c9b816188bfa5edee9f5f197933e735a291f0dca28e3d53f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
